# SPDX-FileCopyrightText: 2025 Ben Jarvis
# SPDX-License-Identifier: Unlicense

name: REUSE Compliance Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install reuse tool
      run: |
        pip install --upgrade pip
        pip install reuse
        
    - name: Run REUSE lint
      run: |
        reuse lint